- name: Deploying pet-clinic
  hosts: app_server

  tasks:
    - name: Create a Directory 
      become: yes
      become_user: root
      file:
        path: /opt/jars
        state: directory
    - name: download jar from Jfrog artifactory
      become: yes
      become_user: root    
      get_url:
        url: http://3.110.222.216:8082/artifactory/pet-clinic/spring-petclinic-2.7.0-SNAPSHOT.jar
        dest: /opt/jars
    - name: Make my directory tree readable
      become: yes
      become_user: root      
      file:
        path: /opt/jars
        mode: 0755
        recurse: yes     
    - name: Deploy the Jar file
      ansible.builtin.shell: cd /opt/jars ; java -jar spring-petclinic-2.7.0-SNAPSHOT.jar 
