- name: Deploying pet-clinic
  hosts: app_server

  tasks:
    - name: Create a Directory 
      become: yes
      become_user: root
      file:
        path: /opt/jars
        state: directory
    - name: download jar from Jfrog artifactory
      become: yes
      become_user: root    
      get_url:
        url: http://{{JFROG_SERVERIP}}:8082/artifactory/pet-clinic/spring-petclinic-2.7.0-SNAPSHOT.jar
        dest: /opt/jars
    - name: Make my directory tree readable
      become: yes
      become_user: root
      file:
        path: /opt/jars
        mode: 0755
        recurse: yes
    - name: copy service file
      become: yes
      become_user: root    
      copy:
        src: /var/jenkins-new/workspace/DeployPetclinic/petclinic.service
        dest: /etc/systemd/system/petclinic.service
        mode: 0774
    - name: running ...
      become: yes
      become_user: root    
      systemd:
        name: petclinic
        state: started
      
