apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic-service
    visualize: 'true'
  name: vets-service
#  annotations:
#    auth.istio.io/8081: NONE
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
#  - name: http-management
#    port: 8081
#    targetPort: 8081
  selector:
    app: vets-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic-pod
  template:
    metadata:
      labels:
        app: petclinic-pod
    spec:
      containers:
        - name: dobby
          image: thecasualcoder/dobby
          ports:
            - containerPort: 4444
          readinessProbe:
            httpGet:
              path: /readiness
              port: 4444
            initialDelaySeconds: 20
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 4444
            initialDelaySeconds: 20
            periodSeconds: 3
          env:
            - name: VERSION
              value: "5.0"